FROM python:3.8.3-slim-buster
FROM python:3.8.3-slim-buster

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    procps vim less

RUN groupadd -g 1337 cornershop && \
    useradd -m -d /opt/cornershop -u 1337 -g cornershop cornershop

USER cornershop
WORKDIR /opt/cornershop
ENV PATH /opt/cornershop/.local/bin:$PATH
COPY --chown=cornershop:cornershop --from=0 /opt/cornershop/.local /opt/cornershop/.local

ADD --chown=cornershop:cornershop .docker/docker-entrypoint.sh /
ADD --chown=cornershop:cornershop .docker/dev /usr/local/bin/

ENTRYPOINT ["/docker-entrypoint.sh"]